---
title: "Untitled"
author: "Ben Marwick"
date: "January 8, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read_in_the_data}
library(ktc11)
library(knitr)
the_data <- read_in_the_data()
# while the data was collected we stored it here: https://catalyst.uw.edu/gopost/conversation/bmarwick/628803/post/2229534#2229534 and https://docs.google.com/spreadsheets/d/1_a20envyJUBA69NfSyLu0JniVUxnyKzAePUwQFrkS64/edit?pref=2&pli=1#gid=0
```


```{r icp_aes_data_summary}
icp_aes_data <- icp_aes_data_summary(the_data$ktc11_raw_ICP_data)

# subset elements related to human occupation and environmental events
 
kable(icp_aes_data)

# correlation matrix of elements of interest
icp_aes_data_subset_cor <- round(cor(icp_aes_data),2)
kable(icp_aes_data_subset_cor)

# icp_aes_data_subset_cor_long <- long_corr_matrix(icp_aes_data_subset)
# interesting_pos <- icp_aes_data_subset_cor_long %>% filter(cor > 0.8 & p < 0.05)
# interesting_neg <- icp_aes_data_subset_cor_long %>% filter(cor < 0 & p < 1)

# cluster analysis of contexts useing elemental data
d <- dist(icp_aes_data, method = "euclidean") # distance matrix
#
# Then do the cluster analysis and plot dendrogram
plot(hclust(d, method="ward.D2"))
#
```